baseURL = "https://codywilbourn.com/"
languageCode = "en-us"
title = "Cody Wilbourn"
theme = "ananke"
googleAnalytics = "UA-119876273-1"
featured_image = "/img/spiration-dark.png"

[params]
  author = "Cody Wilbourn"
  custom_css = ["/css/custom.css"]
  featured_image = "/img/spiration-dark.png"
  recent_posts_number = 5
  twitter = "https://twitter.com/codywilbourn"
  github = "https://github.com/codywilbourn"
  linkedin = "https://www.linkedin.com/in/codywilbourn/"

[menu]
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
  [[menu.main]]
    name = "About"
    url = "/about/"
    

[permalinks]
  post = "/:year/:month/:day/:title"
